### ISSUE TITLE
Google accounts and Users are not connected

### ISSUE THREAD

**Issue by Armetiis** [SwEnt-Fall-2024-Group-22/Cyrcle#109]
We need to establish a connection between the Google account used for Firebase Authentication and the corresponding user object in our database. This linkage is crucial for properly setting the current user in the UserViewModel upon login.

### Current Situation
There's no automatic association between the Firebase Auth user and our database user.

### What we want
When a user logs in with their Google account, we should be able to:
- Retrieve the corresponding user object from our database.
- Set this user as the current user in the UserViewModel.

**Comment by matttsss** [comment]
Closed by #142
