### ISSUE TITLE
Toggle between light and dark mode doesn't remember state

### ISSUE THREAD

**Issue by Armetiis** [SwEnt-Fall-2024-Group-22/Cyrcle#174]
In particular, disconnects user (user signed in gets considered as guest)

To replicate the bug:
- Sign in the app with google
- Toggle the light/dark mode
- Try switching to Profile tab: you'll see you will be logged in as guest (you cannot add parkings or anything either)

Other effects: toggle dark/light mode while on a detail screen unselects the parking (display screen with text "No parking selected, shoud not happen")

**Comment by sean-prz** [comment]
Fixed by @Pijukai
