### ISSUE TITLE
BugFix : camera recenters on puck and advanced mode resetting when leaving and coming back to map. 

### ISSUE THREAD

**Issue by Pijukai** [SwEnt-Fall-2024-Group-22/Cyrcle#275]
1. Fix camera recenters on the map when changing screen and coming back. 
2. Fix advanced mode not persistent when switching screen
3. Refactor Logic in map Screen to prevent bugs coming from the map being destroyed when switching screen.

**Comment by sean-prz** [comment]
If you have time you can assign yourself on #190, it seems deeply linked to what you will try to fix this sprint
