### ISSUE TITLE
Map screen preview cards not displaying upon marker click

### ISSUE THREAD

**Issue by Armetiis** [SwEnt-Fall-2024-Group-22/Cyrcle#343]
In some situations, clicking a marker centers the camera around it but does not display the card. See for example the video below

https://github.com/user-attachments/assets/408cfcc6-4255-4e2d-8eba-e9d0ed049987

Now the cause of the bug is not identified yet. How to replicate it is not very clear either, but it is usually triggered when:
- Like in the video above, we change the zoom level and try to click on markers
- Apply filters on mapscreen also triggers the bug

Note that it is not related to the zoom levels nor the filters themselves, as going for example to list screen and coming back to map screen fixes the bug

**Comment by sean-prz** [comment]
That is for sure the worst bug we have encountered, tried for 1 hour the debugging guide with no success
