### ISSUE TITLE
Parking display coherence on advanced mode

### ISSUE THREAD

**Issue by andrepeiry** [SwEnt-Fall-2024-Group-22/Cyrcle#401]
On the left picture, parkings that only is a point is displayed, but when zooming in (right image), it has disappeared

<img src="https://github.com/user-attachments/assets/e80cee96-9dad-4ef2-b77f-e077fb79e66f" width="200"> <img src="https://github.com/user-attachments/assets/45636519-7509-4783-a68d-8873cd2005bb" width="200">

**Comment by sean-prz** [comment]
it hasn't disappeared if you really look you can see it.
The thing is that it is very very tiny with an area almost 0 so it doesn't show on the map.
To fix this we should assert a minimum area for creating new parking just like we assert a maximum size.
But will we have time, probably not.

**Comment by andrepeiry** [comment]
Oh, I see !
Sorry for reporting it as it was expected behavior, I'll close the issue.
