### ISSUE TITLE
Parking data  is out of sync with database when changed.

### ISSUE THREAD

**Issue by sean-prz** [SwEnt-Fall-2024-Group-22/Cyrcle#407]
There is some changes that are updating the database but not the local cache, making it stale.
For example  :

- Add/Delete a review 
- Add/Delete an Image

If you perform any of this action, it will shows on the UI at first but when navigating between different screens it will disappear. 

Example :
_You can see the review disappearing_
[Screen_recording_20241212_211326.webm](https://github.com/user-attachments/assets/a292d0ef-6025-4684-a43d-70f169b58dc1)

**Comment by sean-prz** [comment]
**This happens because the cache is not updated**

I updated the cache in the following function of the parkingviewmodel : 
`handlenewreview`, `handlereviewdeletion`, `handleReviewUpdate`, and `uploadPicture`

This seems to solve the following problem : 
- adding a review (does not update the score on refresh of the screen) 
- deleting a review (does not update the score on refresh of the screen)
- modifying a review, (does not update the score on refresh of the screen)
- Adding a picture (does not show the picture on refresh of the screen)
@LouisJamesVasseur  There is probably some other case, that I am missing, can you list them if you have any

**Comment by LouisJamesVasseur** [comment]
> **This happens because the cache is not updated**
> 
> I updated the cache in the following function of the parkingviewmodel : `handlenewreview`, `handlereviewdeletion`, `handleReviewUpdate`, and `uploadPicture`
> 
> This seems to solve the following problem :
> 
> * adding a review (does not update the score on refresh of the screen)
> * deleting a review (does not update the score on refresh of the screen)
> * modifying a review, (does not update the score on refresh of the screen)
> * Adding a picture (does not show the picture on refresh of the screen)
>   @LouisJamesVasseur  There is probably some other case, that I am missing, can you list them if you have any

Main issue I've IDed is linked to deletion: deleting a Parking image doesn't reflect in the UI until reload, and deleting a Parking (from admin screen) same thing

**Comment by sean-prz** [comment]
@LouisJamesVasseur AH ok I was not aware of the deletion of a parking issue, I will try to handle that too

**Comment by LouisJamesVasseur** [comment]
> @LouisJamesVasseur AH ok I was not aware of the deletion of a parking issue, I will try to handle that too

It's the issue from my PR last week if you remember

**Comment by sean-prz** [comment]
I am gonna make a quick draft so you can test and see what cases am I missing @LouisJamesVasseur

**Comment by LouisJamesVasseur** [comment]
Sounds good
